# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04" # bento is a better maintained version for Vagrant
  config.vm.box_version = "2.3.1"
  
  # fix for bento version 2.3.2
  #config.vm.provider "virtualbox" do |vb|
  #  vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  #end

  # use Vagrant's insecure key
  config.ssh.insert_key = false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  
  PROVISION_FILE = File.expand_path("../../../packer/requirements.sh")
  config.vm.provision "shell", path: PROVISION_FILE, :privileged => true
  
end
