################################################################
# Defaults
################################################################
defaultEntryPoints = ["http","https"]
################################################################
# Web configuration backend
################################################################
[web]
address = ":8081"
