################################################################
# Defaults
################################################################
defaultEntryPoints = ["http","https"]
# InsecureSkipVerify : If set to true invalid SSL certificates are accepted for backends.
# Note: This disables detection of man-in-the-middle attacks so should only be used on secure backend networks.
insecureSkipVerify = true
################################################################
# Web configuration backend
################################################################
[web]
address = ":8081"
