---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account
  namespace: storage-heketi
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: storage-heketi-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: heketi-service-account
  namespace: storage-heketi
